In [1]:
import pandas as pd

In [2]:
matches = pd.read_csv("matches.csv", index_col=0)

In [3]:
matches.head()

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,Match Report,NaN,13.0,1.0,18.7,1.0,1.0,1.0,2023,Manchester City
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,Match Report,NaN,19.0,7.0,17.5,0.0,0.0,0.0,2023,Manchester City
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,Match Report,NaN,21.0,10.0,16.2,1.0,0.0,0.0,2023,Manchester City
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,Match Report,NaN,18.0,5.0,14.1,0.0,0.0,0.0,2023,Manchester City
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,Match Report,NaN,17.0,9.0,14.8,0.0,0.0,0.0,2023,Manchester City

In [5]:
matches.shape

(2280, 27)

In [6]:
38 * 20 * 3

2280

In [7]:
matches["team"].value_counts()

team
Manchester City             114
Arsenal                     114
Manchester United           114
Newcastle United            114
Liverpool                   114
Brighton and Hove Albion    114
Aston Villa                 114
Tottenham Hotspur           114
Crystal Palace              114
Everton                     114
Chelsea                     114
Wolverhampton Wanderers     114
West Ham United             114
Leeds United                114
Southampton                 114
Leicester City              114
Brentford                    76
Fulham                       76
Burnley                      76
Nottingham Forest            38
Bournemouth                  38
Watford                      38
Norwich City                 38
West Bromwich Albion         38
Sheffield United             38
Name: count, dtype: int64

In [8]:
matches[matches["team"] == "Chelsea"]

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,match report,notes,sh,sot,dist,fk,pk,pkatt,season,team
0,2022-08-06,17:30,Premier League,Matchweek 1,Sat,Away,W,1,0,Everton,...,Match Report,NaN,14.0,5.0,16.1,1.0,1.0,1.0,2023,Chelsea
1,2022-08-14,16:30,Premier League,Matchweek 2,Sun,Home,D,2,2,Tottenham,...,Match Report,NaN,16.0,3.0,17.2,0.0,0.0,0.0,2023,Chelsea
2,2022-08-21,14:00,Premier League,Matchweek 3,Sun,Away,L,0,3,Leeds United,...,Match Report,NaN,14.0,3.0,19.8,0.0,0.0,0.0,2023,Chelsea
3,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,2,1,Leicester City,...,Match Report,NaN,7.0,4.0,14.6,0.0,0.0,0.0,2023,Chelsea
4,2022-08-30,19:45,Premier League,Matchweek 5,Tue,Away,L,1,2,Southampton,...,Match Report,NaN,10.0,4.0,14.5,0.0,0.0,0.0,2023,Chelsea
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51,2021-05-01,17:30,Premier League,Matchweek 34,Sat,Home,W,2,0,Fulham,...,Match Report,NaN,9.0,5.0,14.4,1.0,0.0,0.0,2021,Chelsea
53,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Away,W,2,1,Manchester City,...,Match Report,NaN,12.0,5.0,22.3,1.0,0.0,0.0,2021,Chelsea
54,2021-05-12,20:15,Premier League,Matchweek 36,Wed,Home,L,0,1,Arsenal,...,Match Report,NaN,19.0,4.0,15.0,0.0,0.0,0.0,2021,Chelsea
56,2021-05-18,20:15,Premier League,Matchweek 37,Tue,Home,W,2,1,Leicester City,...,Match Report,NaN,16.0,5.0,13.8,0.0,1.0,1.0,2021,Chelsea
57,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Away,L,1,2,Aston Villa,...,Match Report,NaN,23.0,7.0,15.9,0.0,0.0,0.0,2021,Chelsea

In [9]:
matches["round"].value_counts()

round
Matchweek 1     60
Matchweek 2     60
Matchweek 3     60
Matchweek 4     60
Matchweek 5     60
Matchweek 6     60
Matchweek 8     60
Matchweek 9     60
Matchweek 10    60
Matchweek 11    60
Matchweek 13    60
Matchweek 14    60
Matchweek 15    60
Matchweek 16    60
Matchweek 17    60
Matchweek 18    60
Matchweek 19    60
Matchweek 20    60
Matchweek 7     60
Matchweek 21    60
Matchweek 22    60
Matchweek 23    60
Matchweek 12    60
Matchweek 24    60
Matchweek 25    60
Matchweek 26    60
Matchweek 27    60
Matchweek 29    60
Matchweek 30    60
Matchweek 31    60
Matchweek 33    60
Matchweek 34    60
Matchweek 28    60
Matchweek 35    60
Matchweek 36    60
Matchweek 37    60
Matchweek 32    60
Matchweek 38    60
Name: count, dtype: int64

In [11]:
matches.dtypes

date             object
time             object
comp             object
round            object
day              object
venue            object
result           object
gf                int64
ga                int64
opponent         object
xg              float64
xga             float64
poss            float64
attendance      float64
captain          object
formation        object
referee          object
match report     object
notes           float64
sh              float64
sot             float64
dist            float64
fk              float64
pk              float64
pkatt           float64
season            int64
team             object
dtype: object

In [12]:
matches["date"] = pd.to_datetime(matches["date"])

In [13]:
matches.dtypes

date            datetime64[ns]
time                    object
comp                    object
round                   object
day                     object
venue                   object
result                  object
gf                       int64
ga                       int64
opponent                object
xg                     float64
xga                    float64
poss                   float64
attendance             float64
captain                 object
formation               object
referee                 object
match report            object
notes                  float64
sh                     float64
sot                    float64
dist                   float64
fk                     float64
pk                     float64
pkatt                  float64
season                   int64
team                    object
dtype: object

In [14]:
matches["venue_code"] = matches["venue"].astype("category").cat.codes

In [15]:
matches["opp_code"] = matches["opponent"].astype("category").cat.codes

In [16]:
matches["hour"] = matches["time"].str.replace(":.+", "", regex=True).astype("int")

In [17]:
matches["day_code"] = matches["date"].dt.dayofweek

In [18]:
matches["target"] = (matches["result"] == "W").astype("int")

In [19]:
matches

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,1.0,1.0,1.0,2023,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,0.0,0.0,0.0,2023,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,1.0,0.0,0.0,2023,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,0.0,0.0,0.0,2023,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,0.0,0.0,0.0,2023,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,2021-05-02,19:15,Premier League,Matchweek 34,Sun,Away,L,0,4,Tottenham,...,0.0,0.0,0.0,2021,Sheffield United,0,20,19,6,0
39,2021-05-08,15:00,Premier League,Matchweek 35,Sat,Home,L,0,2,Crystal Palace,...,1.0,0.0,0.0,2021,Sheffield United,1,7,15,5,0
40,2021-05-16,19:00,Premier League,Matchweek 36,Sun,Away,W,1,0,Everton,...,0.0,0.0,0.0,2021,Sheffield United,0,8,19,6,1
41,2021-05-19,18:00,Premier League,Matchweek 37,Wed,Away,L,0,1,Newcastle Utd,...,1.0,0.0,0.0,2021,Sheffield United,0,15,18,2,0
42,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,1,0,Burnley,...,0.0,0.0,0.0,2021,Sheffield United,1,5,16,6,1

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier(n_estimators=50, min_samples_split=10, random_state=1)

In [22]:
train = matches[matches["date"] < '2023-01-01']

In [23]:
test = matches[matches["date"] > '2023-01-01']

In [24]:
predictors = ["venue_code", "opp_code", "hour", "day_code"]

In [25]:
rf.fit(train[predictors], train["target"])

RandomForestClassifier(min_samples_split=10, n_estimators=50, random_state=1)

In [26]:
preds = rf.predict(test[predictors])

In [27]:
from sklearn.metrics import accuracy_score

In [28]:
acc = accuracy_score(test["target"], preds)

In [29]:
acc

0.6004672897196262

In [31]:
combined = pd.DataFrame(dict(actual=test["target"], prediction=preds))

In [32]:
pd.crosstab(index=combined["actual"], columns=combined["prediction"])

prediction    0   1
actual
0           208  55
1           116  49

In [34]:
from sklearn.metrics import precision_score

In [35]:
precision_score(test["target"], preds)

np.float64(0.47115384615384615)

In [36]:
grouped_matches = matches.groupby("team")

In [37]:
group = grouped_matches.get_group("Manchester City")

In [38]:
group

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,fk,pk,pkatt,season,team,venue_code,opp_code,hour,day_code,target
1,2022-08-07,16:30,Premier League,Matchweek 1,Sun,Away,W,2,0,West Ham,...,1.0,1.0,1.0,2023,Manchester City,0,23,16,6,1
2,2022-08-13,15:00,Premier League,Matchweek 2,Sat,Home,W,4,0,Bournemouth,...,0.0,0.0,0.0,2023,Manchester City,1,2,15,5,1
3,2022-08-21,16:30,Premier League,Matchweek 3,Sun,Away,D,3,3,Newcastle Utd,...,1.0,0.0,0.0,2023,Manchester City,0,15,16,6,0
4,2022-08-27,15:00,Premier League,Matchweek 4,Sat,Home,W,4,2,Crystal Palace,...,0.0,0.0,0.0,2023,Manchester City,1,7,15,5,1
5,2022-08-31,19:30,Premier League,Matchweek 5,Wed,Home,W,6,0,Nott'ham Forest,...,0.0,0.0,0.0,2023,Manchester City,1,17,19,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,2021-05-01,12:30,Premier League,Matchweek 34,Sat,Away,W,2,0,Crystal Palace,...,1.0,0.0,0.0,2021,Manchester City,0,7,12,5,1
56,2021-05-08,17:30,Premier League,Matchweek 35,Sat,Home,L,1,2,Chelsea,...,0.0,0.0,1.0,2021,Manchester City,1,6,17,5,0
57,2021-05-14,20:00,Premier League,Matchweek 36,Fri,Away,W,4,3,Newcastle Utd,...,1.0,0.0,0.0,2021,Manchester City,0,15,20,4,1
58,2021-05-18,19:00,Premier League,Matchweek 37,Tue,Away,L,2,3,Brighton,...,1.0,0.0,0.0,2021,Manchester City,0,4,19,1,0
59,2021-05-23,16:00,Premier League,Matchweek 38,Sun,Home,W,5,0,Everton,...,0.0,0.0,0.0,2021,Manchester City,1,8,16,6,1

In [39]:
def rolling_averages(group, cols, new_cols):
    group = group.sort_values("date")
    rolling_stats = group[cols].rolling(3, closed='left').mean()
    group[new_cols] = rolling_stats
    group = group.dropna(subset=new_cols)
    return group

In [40]:
cols = ["gf", "ga", "sh", "sot", "dist", "fk", "pk", "pkatt"]
new_cols = [f"{c}_rolling" for c in cols]

In [41]:
new_cols

['gf_rolling',
 'ga_rolling',
 'sh_rolling',
 'sot_rolling',
 'dist_rolling',
 'fk_rolling',
 'pk_rolling',
 'pkatt_rolling']

In [43]:
rolling_averages(group, cols, new_cols)

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
5,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Home,W,1,0,Arsenal,...,5,1,2.000000,2.333333,17.333333,4.666667,19.700000,1.333333,0.333333,0.333333
7,2020-10-24,12:30,Premier League,Matchweek 6,Sat,Away,D,1,1,West Ham,...,5,0,1.333333,2.000000,17.333333,3.666667,18.566667,0.666667,0.000000,0.000000
9,2020-10-31,12:30,Premier League,Matchweek 7,Sat,Away,W,1,0,Sheffield Utd,...,5,1,1.000000,0.666667,16.666667,4.333333,18.933333,0.666667,0.000000,0.000000
11,2020-11-08,16:30,Premier League,Matchweek 8,Sun,Home,D,1,1,Liverpool,...,6,0,1.000000,0.333333,14.333333,6.666667,19.033333,1.000000,0.000000,0.000000
12,2020-11-21,17:30,Premier League,Matchweek 9,Sat,Away,L,0,2,Tottenham,...,5,0,1.000000,0.666667,12.000000,5.666667,20.000000,1.000000,0.000000,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,2,1,Leeds United,...,5,1,3.000000,0.666667,13.666667,8.000000,15.433333,0.000000,0.333333,0.333333
54,2023-05-14,14:00,Premier League,Matchweek 36,Sun,Away,W,3,0,Everton,...,6,1,2.333333,0.666667,14.666667,7.000000,16.366667,0.666667,0.333333,0.666667
56,2023-05-21,16:00,Premier League,Matchweek 37,Sun,Home,W,1,0,Chelsea,...,6,1,2.666667,0.333333,14.000000,5.666667,18.100000,1.333333,0.000000,0.333333
57,2023-05-24,20:00,Premier League,Matchweek 32,Wed,Away,D,1,1,Brighton,...,2,0,2.000000,0.333333,13.666667,4.000000,18.933333,1.333333,0.000000,0.333333
58,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,1,Brentford,...,6,0,1.666667,0.333333,12.333333,3.333333,17.333333,0.666667,0.000000,0.000000

In [44]:
matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

C:\Users\ShriyaAsija\AppData\Local\Temp\ipykernel_9916\4052147919.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  matches_rolling = matches.groupby("team").apply(lambda x: rolling_averages(x, cols, new_cols))

In [45]:
matches_rolling

                                 date   time            comp         round  \
team
Arsenal                 6  2020-10-04  14:00  Premier League   Matchweek 4
                        7  2020-10-17  17:30  Premier League   Matchweek 5
                        9  2020-10-25  19:15  Premier League   Matchweek 6
                        11 2020-11-01  16:30  Premier League   Matchweek 7
                        13 2020-11-08  19:15  Premier League   Matchweek 8
...                               ...    ...             ...           ...
Wolverhampton Wanderers 39 2023-04-29  15:00  Premier League  Matchweek 34
                        40 2023-05-06  15:00  Premier League  Matchweek 35
                        41 2023-05-13  15:00  Premier League  Matchweek 36
                        42 2023-05-20  15:00  Premier League  Matchweek 37
                        43 2023-05-28  16:30  Premier League  Matchweek 38

                            day venue result  gf  ga         opponent  ...  \
team                                                                   ...
Arsenal                 6   Sun  Home      W   2   1    Sheffield Utd  ...
                        7   Sat  Away      L   0   1  Manchester City  ...
                        9   Sun  Home      L   0   1   Leicester City  ...
                        11  Sun  Away      W   1   0   Manchester Utd  ...
                        13  Sun  Home      L   0   3      Aston Villa  ...
...                         ...   ...    ...  ..  ..              ...  ...
Wolverhampton Wanderers 39  Sat  Away      L   0   6         Brighton  ...
                        40  Sat  Home      W   1   0      Aston Villa  ...
                        41  Sat  Away      L   0   2   Manchester Utd  ...
                        42  Sat  Home      D   1   1          Everton  ...
                        43  Sun  Away      L   0   5          Arsenal  ...

                            day_code  target  gf_rolling  ga_rolling  \
team
Arsenal                 6          6       1    2.000000    1.333333
                        7          5       0    1.666667    1.666667
                        9          6       0    1.000000    1.666667
                        11         6       1    0.666667    1.000000
                        13         6       0    0.333333    0.666667
...                              ...     ...         ...         ...
Wolverhampton Wanderers 39         5       0    1.666667    0.666667
                        40         5       1    1.000000    2.666667
                        41         5       0    1.000000    2.000000
                        42         5       0    0.333333    2.666667
                        43         6       0    0.666667    1.000000

                           sh_rolling sot_rolling dist_rolling fk_rolling  \
team
Arsenal                 6    8.000000    3.666667    14.633333   0.666667
                        7    5.666667    3.666667    15.366667   0.000000
                        9    7.000000    3.666667    16.566667   0.666667
                        11   9.666667    4.000000    16.566667   1.000000
                        13   9.666667    2.666667    19.333333   1.000000
...                               ...         ...          ...        ...
Wolverhampton Wanderers 39  11.666667    4.666667    18.700000   0.666667
                        40  11.333333    2.333333    18.800000   0.666667
                        41   8.000000    2.000000    17.766667   0.000000
                        42   7.000000    1.333333    15.600000   0.000000
                        43   8.000000    2.333333    15.333333   0.333333

                            pk_rolling  pkatt_rolling
team
Arsenal                 6     0.000000       0.000000
                        7     0.000000       0.000000
                        9     0.000000       0.000000
                        11    0.000000       0.000000
                        13    0.333333       0.333333
...                                ...            ...
Wolverhampton Wanderers 39    0.333333       0.333333
                        40    0.333333       0.333333
                        41    0.333333       0.333333
                        42    0.000000       0.000000
                        43    0.000000       0.000000

[2202 rows x 40 columns]

In [46]:
matches_rolling = matches_rolling.droplevel('team')

In [47]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
6,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
7,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
9,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
11,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
13,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0,6,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
40,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1,0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
41,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
42,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
43,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [48]:
matches_rolling.index = range(matches_rolling.shape[0])

In [49]:
matches_rolling

,date,time,comp,round,day,venue,result,gf,ga,opponent,...,day_code,target,gf_rolling,ga_rolling,sh_rolling,sot_rolling,dist_rolling,fk_rolling,pk_rolling,pkatt_rolling
0,2020-10-04,14:00,Premier League,Matchweek 4,Sun,Home,W,2,1,Sheffield Utd,...,6,1,2.000000,1.333333,8.000000,3.666667,14.633333,0.666667,0.000000,0.000000
1,2020-10-17,17:30,Premier League,Matchweek 5,Sat,Away,L,0,1,Manchester City,...,5,0,1.666667,1.666667,5.666667,3.666667,15.366667,0.000000,0.000000,0.000000
2,2020-10-25,19:15,Premier League,Matchweek 6,Sun,Home,L,0,1,Leicester City,...,6,0,1.000000,1.666667,7.000000,3.666667,16.566667,0.666667,0.000000,0.000000
3,2020-11-01,16:30,Premier League,Matchweek 7,Sun,Away,W,1,0,Manchester Utd,...,6,1,0.666667,1.000000,9.666667,4.000000,16.566667,1.000000,0.000000,0.000000
4,2020-11-08,19:15,Premier League,Matchweek 8,Sun,Home,L,0,3,Aston Villa,...,6,0,0.333333,0.666667,9.666667,2.666667,19.333333,1.000000,0.333333,0.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2197,2023-04-29,15:00,Premier League,Matchweek 34,Sat,Away,L,0,6,Brighton,...,5,0,1.666667,0.666667,11.666667,4.666667,18.700000,0.666667,0.333333,0.333333
2198,2023-05-06,15:00,Premier League,Matchweek 35,Sat,Home,W,1,0,Aston Villa,...,5,1,1.000000,2.666667,11.333333,2.333333,18.800000,0.666667,0.333333,0.333333
2199,2023-05-13,15:00,Premier League,Matchweek 36,Sat,Away,L,0,2,Manchester Utd,...,5,0,1.000000,2.000000,8.000000,2.000000,17.766667,0.000000,0.333333,0.333333
2200,2023-05-20,15:00,Premier League,Matchweek 37,Sat,Home,D,1,1,Everton,...,5,0,0.333333,2.666667,7.000000,1.333333,15.600000,0.000000,0.000000,0.000000
2201,2023-05-28,16:30,Premier League,Matchweek 38,Sun,Away,L,0,5,Arsenal,...,6,0,0.666667,1.000000,8.000000,2.333333,15.333333,0.333333,0.000000,0.000000

In [50]:
def make_predictions(data, predictors):
    train = data[data["date"] < '2023-01-01']
    test = data[data["date"] > '2023-01-01']
    rf.fit(train[predictors], train["target"])
    preds = rf.predict(test[predictors])
    combined = pd.DataFrame(dict(actual=test["target"], predicted=preds), index=test.index)
    precision=precision_score(test["target"], preds)
    return combined, precision

In [51]:
combined, precision = make_predictions(matches_rolling, predictors + new_cols)

In [52]:
precision

np.float64(0.5306122448979592)

In [53]:
combined

      actual  predicted
89         0          1
90         1          0
91         1          0
92         0          1
93         0          1
...      ...        ...
2197       0          0
2198       1          0
2199       0          0
2200       0          0
2201       0          0

[428 rows x 2 columns]

In [54]:
combined = combined.merge(matches_rolling[["date", "team", "opponent", "result"]], left_index=True, right_index=True)

In [55]:
combined

,actual,predicted,date,team,opponent,result
89,0,1,2023-01-03,Arsenal,Newcastle Utd,D
90,1,0,2023-01-15,Arsenal,Tottenham,W
91,1,0,2023-01-22,Arsenal,Manchester Utd,W
92,0,1,2023-02-04,Arsenal,Everton,L
93,0,1,2023-02-11,Arsenal,Brentford,D
...,...,...,...,...,...,...
2197,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L
2198,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W
2199,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L
2200,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D
2201,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L

In [56]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {
    "Brighton and Hove Albion": "Brighton",
    "Manchester United": "Manchester Utd",
    "Newcastle United": "Newcastle Utd",
    "Tottenham Hotspur": "Tottenham",
    "West Ham United": "West Ham",
    "Wolverhampton Wanderers": "Wolves"
}

mapping = MissingDict(**map_values)

In [58]:
mapping["West Ham United"]

'West Ham'

In [59]:
combined["new_team"] = combined["team"].map(mapping)

In [60]:
combined

,actual,predicted,date,team,opponent,result,new_team
89,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal
90,1,0,2023-01-15,Arsenal,Tottenham,W,Arsenal
91,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal
92,0,1,2023-02-04,Arsenal,Everton,L,Arsenal
93,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal
...,...,...,...,...,...,...,...
2197,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves
2198,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves
2199,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves
2200,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves
2201,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves

In [61]:
merged = combined.merge(combined, left_on=["date", "new_team"], right_on=["date", "opponent"])

In [62]:
merged

,actual_x,predicted_x,date,team_x,opponent_x,result_x,new_team_x,actual_y,predicted_y,team_y,opponent_y,result_y,new_team_y
0,0,1,2023-01-03,Arsenal,Newcastle Utd,D,Arsenal,0,0,Newcastle United,Arsenal,D,Newcastle Utd
1,1,0,2023-01-15,Arsenal,Tottenham,W,Arsenal,0,0,Tottenham Hotspur,Arsenal,L,Tottenham
2,1,0,2023-01-22,Arsenal,Manchester Utd,W,Arsenal,0,1,Manchester United,Arsenal,L,Manchester Utd
3,0,1,2023-02-04,Arsenal,Everton,L,Arsenal,1,0,Everton,Arsenal,W,Everton
4,0,1,2023-02-11,Arsenal,Brentford,D,Arsenal,0,0,Brentford,Arsenal,D,Brentford
...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,0,0,2023-04-29,Wolverhampton Wanderers,Brighton,L,Wolves,1,1,Brighton and Hove Albion,Wolves,W,Brighton
403,1,0,2023-05-06,Wolverhampton Wanderers,Aston Villa,W,Wolves,0,0,Aston Villa,Wolves,L,Aston Villa
404,0,0,2023-05-13,Wolverhampton Wanderers,Manchester Utd,L,Wolves,1,1,Manchester United,Wolves,W,Manchester Utd
405,0,0,2023-05-20,Wolverhampton Wanderers,Everton,D,Wolves,0,0,Everton,Wolves,D,Everton
406,0,0,2023-05-28,Wolverhampton Wanderers,Arsenal,L,Wolves,1,0,Arsenal,Wolves,W,Arsenal

In [63]:
merged[(merged["predicted_x"] == 1) & (merged["predicted_y"] == 0)]["actual_x"].value_counts()

actual_x
1    48
0    38
Name: count, dtype: int64

In [64]:
48 / (48 + 38)

0.5581395348837209

In [65]:
matches.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'sh', 'sot', 'dist', 'fk', 'pk',
       'pkatt', 'season', 'team', 'venue_code', 'opp_code', 'hour', 'day_code',
       'target'],
      dtype='object')